/*
 * Created on 30-Aug-2005
 *
 * @author Graham Stark (graham.stark@virtual-worlds.biz)
 * 
 */
package org.oscr.charts;

/**
 * useful(?) stuff for JFreeChart
 * 
 * @author Graham Stark (graham_s@ifs.org.uk)
 */

// / SVG Support
import java.awt.Dimension;
import java.awt.geom.Rectangle2D;
import java.io.IOException;
import java.io.Writer;

import org.apache.batik.dom.GenericDOMImplementation;
import org.apache.batik.svggen.SVGGeneratorContext;
import org.apache.batik.svggen.SVGGraphics2D;
import org.apache.batik.svggen.SVGGraphics2DIOException;
import org.jfree.chart.JFreeChart;
import org.w3c.dom.DOMImplementation;

public class JPlotUtils {

        // Get a DOMImplementation
        private static DOMImplementation domImpl = GenericDOMImplementation.getDOMImplementation();

        public static void writeChartAsSVG( Writer out, JFreeChart chart, int width, int height ) throws IOException {
                try {
                        org.w3c.dom.Document document = domImpl.createDocument( null, "svg", null );
                        // / Create an SVG Context to customise
                        SVGGeneratorContext ctx = SVGGeneratorContext.createDefault( document );
                        ctx.setComment( "Generated by JFreePlotUtils using Batik SVG Generator" );
                        // Create an instance of the SVG Generator
                        SVGGraphics2D svgGenerator = new SVGGraphics2D( ctx, false );
                        svgGenerator.setSVGCanvasSize( new Dimension( width, height ) );
                        chart.draw( svgGenerator, new Rectangle2D.Double( 0, 0, width, height ), null );
                        svgGenerator.stream( out, false );
                } catch ( SVGGraphics2DIOException ioe ) {
                        throw new IOException( ioe.toString() );
                }
        }
}